# Generated by Django 4.1.6 on 2023-02-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('document', models.CharField(choices=[('dni', 'dni'), ('pasaporte', 'pasaporte'), ('cedula de identidad', 'cedula de identidad')], max_length=50, verbose_name='Tipo de documento')),
                ('number_document', models.CharField(max_length=15, verbose_name='Numero de documento')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
    ]
