# Generated by Django 4.1.6 on 2023-02-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('document', models.CharField(choices=[('dni', 'DNI'), ('cedula de identidad', 'Cédula de identidad'), ('pasaporte', 'Pasaporte')], max_length=50, verbose_name='Tipo de documento')),
                ('number_document', models.CharField(max_length=15, verbose_name='Numero de documento')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.DeleteModel(
            name='CourseChef',
        ),
    ]
