# Generated by Django 4.1.6 on 2023-02-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_delete_coursechef'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.CharField(choices=[('Curso Pasteleria', 'Curso Pasteleria'), ('Curso Chef', 'Curso Chef')], default='', max_length=20, verbose_name='Curso a elegir'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='document',
            field=models.CharField(choices=[('dni', 'DNI'), ('pasaporte', 'Pasaporte'), ('cedula de identidad', 'Cédula de identidad')], max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
