# Generated by Django 4.1.6 on 2023-02-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(choices=[('Curso Chef', 'Curso Chef'), ('Curso Pasteleria', 'Curso Pasteleria')], max_length=20, verbose_name='Curso a elegir'),
        ),
        migrations.AlterField(
            model_name='course',
            name='document',
            field=models.CharField(choices=[('cedula de identidad', 'Cédula de identidad'), ('dni', 'DNI'), ('pasaporte', 'Pasaporte')], max_length=20, verbose_name='Tipo de documento'),
        ),
    ]
