# Generated by Django 4.1.6 on 2023-02-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default='', upload_to='recipes', verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipes',
            name='ingredients',
            field=models.CharField(max_length=250, verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe',
            field=models.CharField(max_length=1000, verbose_name='Receta'),
        ),
    ]
