# Generated by Django 4.1.6 on 2023-02-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Descripcion'),
        ),
    ]
